# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ErosionRisk
                                 A QGIS plugin
 This plugin estimated the soil erosion risk based on different RUSLE methodologies.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-16
        copyright            : (C) 2021 by Duarte et al
        email                : liaduarte@fc.up.pt
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ErosionRisk class from file ErosionRisk.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .erosion_risk import ErosionRisk
    return ErosionRisk(iface)
